/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package teams;

import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author pranav
 */
public class transpcript extends javax.swing.JFrame {

    /**
     * Creates new form transpcript
     */
    public transpcript() {
        initComponents();
    }
Connection con;
   
     PreparedStatement pst;
      PreparedStatement pst1;
       ResultSet rs;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtregno = new javax.swing.JTextField();
        txttname = new javax.swing.JTextField();
        txtcaptain = new javax.swing.JTextField();
        txtcoachid = new javax.swing.JTextField();
        txtmanager = new javax.swing.JTextField();
        txtpoints = new javax.swing.JTextField();
        txtranking = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtcoach = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtplayers = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtarea = new javax.swing.JTextArea();
        txttranscript = new javax.swing.JButton();
        txtexit = new javax.swing.JButton();
        txtprint = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(900, 500));
        setMinimumSize(new java.awt.Dimension(900, 500));
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 255, 153,20));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("team details"));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("TEAM ID");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("TEAM NAME");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("CAPTAIN ID");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("COACH  ID");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("MANAGER ");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setText("TOTAL POINTS");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setText("RANKING");

        txtregno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtregnoActionPerformed(evt);
            }
        });
        txtregno.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtregnoKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtregnoKeyTyped(evt);
            }
        });

        txttname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttnameActionPerformed(evt);
            }
        });

        txtcaptain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcaptainActionPerformed(evt);
            }
        });

        txtpoints.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpointsActionPerformed(evt);
            }
        });

        txtranking.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtrankingActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setText("COACH ");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel9.setText("TOTAL PLAYERS");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel9)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel1)
                                        .addComponent(jLabel2))
                                    .addGap(15, 15, 15)))
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel8)
                            .addComponent(jLabel5))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(23, 23, 23)))
                    .addComponent(jLabel6))
                .addGap(44, 44, 44)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtpoints, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtmanager, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtcaptain, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(txtplayers, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE)
                        .addComponent(txtcoach, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtregno, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txttname, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtcoachid, javax.swing.GroupLayout.Alignment.LEADING))
                    .addComponent(txtranking, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(51, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtregno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txttname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtplayers, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtcaptain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtcoachid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtcoach, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtmanager, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(txtpoints, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtranking, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(66, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(20, 20, 389, 390);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("details"));
        jPanel2.setMaximumSize(new java.awt.Dimension(900, 500));
        jPanel2.setMinimumSize(new java.awt.Dimension(900, 500));

        txtarea.setColumns(20);
        txtarea.setFont(new java.awt.Font("Monospaced", 1, 13)); // NOI18N
        txtarea.setRows(5);
        jScrollPane1.setViewportView(txtarea);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 401, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 415, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(jPanel2);
        jPanel2.setBounds(460, 10, 413, 430);

        txttranscript.setText("TRANSCRIPT");
        txttranscript.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttranscriptActionPerformed(evt);
            }
        });
        getContentPane().add(txttranscript);
        txttranscript.setBounds(50, 430, 130, 23);

        txtexit.setText("EXIT");
        txtexit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtexitActionPerformed(evt);
            }
        });
        getContentPane().add(txtexit);
        txtexit.setBounds(220, 430, 55, 23);

        txtprint.setText("PRINT");
        txtprint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtprintActionPerformed(evt);
            }
        });
        getContentPane().add(txtprint);
        txtprint.setBounds(310, 440, 90, 23);

        jLabel10.setIcon(new javax.swing.ImageIcon("C:\\Users\\pranav\\Downloads\\fb.jpg")); // NOI18N
        jLabel10.setText("jLabel10");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(0, -10, 1044, 510);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtcaptainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcaptainActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcaptainActionPerformed

    private void txtpointsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpointsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpointsActionPerformed

    private void txttnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txttnameActionPerformed
    private JFrame frame;
    private void txtexitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtexitActionPerformed
        // TODO add your handling code here:
        frame=new JFrame("Exit");
       if(JOptionPane.showConfirmDialog(frame,"Confirm if u to exit","standings System",JOptionPane.YES_NO_OPTION)==JOptionPane.YES_NO_OPTION){
           System.exit(0);
       }

    }//GEN-LAST:event_txtexitActionPerformed

    private void txtregnoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtregnoKeyPressed
        // TODO add your handling code here:
         if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            try {
                Class.forName("com.mysql.jdbc.Driver");
                con=DriverManager.getConnection("jdbc:mysql://localhost/footballdb","root","");
                    String teamid=txtregno.getText();
                    String tname=txttname.getText();
                    String players=txtplayers.getText();
                    String captainid=txtcaptain.getText();
                    String coachid=txtcoachid.getText();
                    String manager=txtmanager.getText();
                    
                    
                pst=con .prepareStatement("select teamid,tname,total_no_of_players,captain,coachid,manager_name from teams where teamid=?");
                pst.setString(1, teamid);
                rs=pst.executeQuery();
                if(rs.next()==false){
                     JOptionPane.showMessageDialog(this,"TEAM NOT FOUND.......");
                }
                else{
                    
                    String team=rs.getString("tname");
                    txttname.setText(team.trim());
                    String player=rs.getString("total_no_of_players");
                    txtplayers.setText(player.trim());
                    String captain=rs.getString("captain");
                    txtcaptain.setText(captain.trim());
                    String coachi=rs.getString("coachid");
                    txtcoachid.setText(coachi.trim());
                    String man=rs.getString("manager_name");
                    txtmanager.setText(man.trim());
                                     
                    
                    
                }
            
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(transpcript.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(transpcript.class.getName()).log(Level.SEVERE, null, ex);
            }
            if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            try {
                Class.forName("com.mysql.jdbc.Driver");
                con=DriverManager.getConnection("jdbc:mysql://localhost/footballdb","root","");
                    String teamid=txtregno.getText();
                    String tname=txttname.getText();
                    String points=txtpoints.getText();
                    String ranking=txtranking.getText();
                   
                    
                    
                pst=con .prepareStatement("select teamid,tname,total_points,ranking from standings where teamid=?");
                pst.setString(1, teamid);
                rs=pst.executeQuery();
                if(rs.next()==false){
                     JOptionPane.showMessageDialog(this,"TEAM NOT FOUND.......");
                }
                else{
                    
                    String team=rs.getString("tname");
                    txttname.setText(team.trim());
                    String poi=rs.getString("total_points");
                    txtpoints.setText(poi.trim());
                    String rank=rs.getString("ranking");
                    txtranking.setText(rank.trim());
                    
                                     
                    
                    
                }
            
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(transpcript.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(transpcript.class.getName()).log(Level.SEVERE, null, ex);
            }
             
        }
             
        }
         if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            try {
                Class.forName("com.mysql.jdbc.Driver");
                con=DriverManager.getConnection("jdbc:mysql://localhost/footballdb","root","");
                    String teamid=txtregno.getText();
                    String coach=txtcoach.getText();
                    
                    
                pst=con .prepareStatement("select teamid,cname from coach where teamid=?");
                pst.setString(1, teamid);
                rs=pst.executeQuery();
                if(rs.next()==false){
                     JOptionPane.showMessageDialog(this,"TEAM NOT FOUND.......");
                }
                else{
                    
                    String coa=rs.getString("cname");
                    txtcoach.setText(coa.trim());
                    
                }
            
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(transpcript.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(transpcript.class.getName()).log(Level.SEVERE, null, ex);
            }
             
        }
    }//GEN-LAST:event_txtregnoKeyPressed

    private void txtrankingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtrankingActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtrankingActionPerformed

    private void txttranscriptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttranscriptActionPerformed
        // TODO add your handling code here:
        txtarea.setText("******************************************************************\n");
         txtarea.setText(txtarea.getText()+"    DOMESTIC FOOTBALL MANAGEMENT SYSTEM    \n");
        txtarea.setText(txtarea.getText()+"****************************************************************\n");
       Date obj= new Date();
       String date= obj.toString();
       txtarea.setText(txtarea.getText()+"\n"+date);
       txtarea.setText(txtarea.getText()+"\nTEAMID:"+txtregno.getText()+"\n\n"); 
       txtarea.setText(txtarea.getText()+"TEAM NAME:"+txttname.getText()+"\n\n");
        txtarea.setText(txtarea.getText()+"TOTAL PLAYERS:"+txtplayers.getText()+"\n\n");  
        txtarea.setText(txtarea.getText()+"CAPTAIN ID:"+txtcaptain.getText()+"\n\n");
        txtarea.setText(txtarea.getText()+"COACH ID:"+txtcoachid.getText()+"\n\n");
        txtarea.setText(txtarea.getText()+"COACH:"+txtcoach.getText()+"\n\n");
        txtarea.setText(txtarea.getText()+"MANAGER:"+txtmanager.getText()+"\n\n");
        txtarea.setText(txtarea.getText()+"TOTAL POINTS:"+txtpoints.getText()+"\n\n");
        txtarea.setText(txtarea.getText()+"RANKING:"+txtranking.getText()+"\n\n");
        txtarea.setText(txtarea.getText()+"\n                               Signature");
           
         
    }//GEN-LAST:event_txttranscriptActionPerformed

    private void txtregnoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtregnoKeyTyped
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtregnoKeyTyped

    private void txtregnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtregnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtregnoActionPerformed

    private void txtprintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtprintActionPerformed
        // TODO add your handling code here:
        try{
            txtarea.print();
        }
        catch(Exception e){
    }//GEN-LAST:event_txtprintActionPerformed
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(transpcript.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(transpcript.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(transpcript.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(transpcript.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new transpcript().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtarea;
    private javax.swing.JTextField txtcaptain;
    private javax.swing.JTextField txtcoach;
    private javax.swing.JTextField txtcoachid;
    private javax.swing.JButton txtexit;
    private javax.swing.JTextField txtmanager;
    private javax.swing.JTextField txtplayers;
    private javax.swing.JTextField txtpoints;
    private javax.swing.JButton txtprint;
    private javax.swing.JTextField txtranking;
    private javax.swing.JTextField txtregno;
    private javax.swing.JTextField txttname;
    private javax.swing.JButton txttranscript;
    // End of variables declaration//GEN-END:variables
}
